---
title: "18-09-2023"
output: html_document
date: "2023-09-18"
---

```{r}
# Carica i pacchetti neccessari
library(greenbrown)
library(sf)
library(dplyr)
library(lubridate)
library(raster)
library(zoo)
library(DBEST)
```

```{r}
# Carica il file dell'ndvi
# NDVI_VALUES <- st_read("G:/Altri computer/Il_mio_computer/DOTTORATO/PROGETTI/OLIVASTRO_PAULILATINO/REGRESSIONE/VETTORIALI/NDVI_VALUES/merged_data_ndvi.shp")
```

```{r}
# Imposta l'opzione scipen su un valore elevato per eliminare la notazione esponenziale dei valori
options(scipen = 999)
```

```{r}
# Seleziona il codice della chioma di interesse
data0 <- NDVI_VALUES[NDVI_VALUES$COD == 'ORTERI2_53', ]

ts <- ts(data0$ndvi, start = c(2018, 1), end = c(2023, 8), frequency = 12)

fit <- lm(ndvi ~ date, data = data0)

# Estrai i coefficienti
intercept <- coef(fit)[1]
slope <- coef(fit)[2]

area <- unique(data0$COD)

# Equazione della linea di regressione
eq = paste0(" Y =", round(slope, 8), "*x + ", round(intercept,8))

# Crea il grafico di dispersione dei dati
plot(data0$date,data0$ndvi, type = "p")
# Sovrapponi la linea retta basata sui coefficienti del modello di regressione
abline(a = intercept, b = slope, col = "red")

# Aggiungi il titolo e il sottotitolo
title(main = area)
mtext(eq, side = 3, line = 0.3)
```

```{r}
dbest_analysis <- DBEST::DBEST(data = ts, data.type = "cyclical", algorithm = "change detection", breakpoints.no= 10, first.level.shift= 0.1, second.level.shift=0.2, duration=12, distance.threshold="default", alpha=0.05, plot="on" )
```

```{r}
trend_dbest <- dbest_analysis$Fit

trend_df <- as.data.frame(trend_dbest, row.names = FALSE)
colnames(trend_df) <- "ndvi"

trend_df$date <- data0$date

plot(trend_df$date, trend_df$ndvi, type = "l")
```


```{r}
# Crea il grafico di dispersione dei dati
plot(data0$date, data0$ndvi, type = "p", xlab = "Date", ylab = "NDVI values")

# Linea di tendenza 1 (colore blu)
lines(smooth.spline(data0$date, data0$ndvi), col = "blue")

# Linea di tendenza 2 (colore verde)
lines(trend_df$date, trend_df$ndvi, type = "l", col = "black")

# Sovrapponi la linea retta basata sui coefficienti del modello di regressione (colore rosso)
abline(a = intercept, b = slope, col = "red")

# Aggiungi il titolo e il sottotitolo
title(main = area)
mtext(eq, side = 3, line = 0.3)
```




















